### ISSUE TITLE
Acionar alarme

### ISSUE THREAD

**Issue by joaofidelix** [elvis-epx/alarme-intelbras#1]
Olá. 
você saberia dizer se tem algum protocolo que possibilite acionar a central via receptor IP?

muito obrigado pelo projeto!!

**Comment by Marlonzao** [comment]
Olá,

Também tenho interesse na dúvida do João.

Obrigado.

**Comment by renatomarcio** [comment]
Estou procurando pela mesma coisa. Estou tentando fazer a integração de um alarme AMT 8000 com Home Assistant. A idéia é conseguir através de uma interface IHM smart home ativar e desativar o alarme, obter alertas de intrusão. Fazer algo muito parecido do que o aplicativo Guardian já faz, só que integrado.

**Comment by caarlos0** [comment]
#3

**Comment by elvis-epx** [comment]
O utilitário 'comandar', introduzido recentemente no código-fonte, faz isto.
