### ISSUE TITLE
Retransmitir sinal

### ISSUE THREAD

**Issue by joaofidelix** [elvis-epx/alarme-intelbras#2]
Olá. 
Seria possível de forma fácil, fazer um replay das informações recebidas da central, para outro Server ?

Motivação:
- Minha central é monitorada com empresa. Diante disto, a configuração de servidor 1 na central está apontando para o IP da empresa de monitoramento. 
- O servidor 2 da central está apontando para a Intelbras. 
- Com isso perco a possibilidade de apontar para meu IP interno. Por que não tem mais servidores de configuração. 

Minha ideia seria colocar meu IP interno no servidor 2. 
E via programação, toda mensagem da central que chegasse para o servidor interno, eu faria um replay para amt.Intelbras.com.br.

**Comment by elvis-epx** [comment]
Possível, certamente é. Teria de implementar. O principal ponto seria o tratamento das mensagens de retorno do servidor Intelbras (quase sempre apenas um ACK de um byte).

Se não envolver a questão de upload de fotos do sensor IVP 8000 Pet, não é muito difícil.

**Comment by renatomarcio** [comment]
Tenho observado uma tendência muito grande de aplicativos tipo o Home Assistant passarem a dominar este cenário de automação residencial, incluindo monitoramento e segurança. 
Tenho me coçado para arrumar um tempo para desenvolver uma integração entre a central da Intelbras e o Home Assistant, mas sem chance are agora. 
A plataforma Intelbras fragmentado e sem integração como é hoje será em breve substituída por nova tecnologia. 

É preciso integrar interfonai IP, CFTV e Alarme em um único ambiente democrático, de fácil uso e alta disponibilidade ao usuário.

**Comment by boemekeld** [comment]
Olá, sabem me dizer se tivemos alguma evolução por aqui?

Estou na mesma situação. Querendo dedicar tempo para integrar minha central ao Home Assistant e com o mesmo problema de estar com os 2 IPs em uso. Pensei em fazer esse replay (mas para o servidor da empresa de monitoramento ao invés do servidor cloud da Intelbras, para que o app continue com acesso caso o Home Assistant tenha algum problema).

**Comment by elvis-epx** [comment]
Uma pergunta - minha central sempre comunicou com o Intelbras Cloud sem configurar IP explicitamente. Certeza que essa comunicação com o cloud ocupa um dos dois IPs do Receptor IP?

**Comment by boemekeld** [comment]
Boa pergunta. Pela configuração tudo indica que sim, mas não testei remover do 2 slot.

**Comment by elvis-epx** [comment]
Acredito que funcione, uma vez configurei inadvertidamente os dois IPs para o mesmo Receptor IP (o meu) e a nuvem continuou funcionando, alias e o que uso para fazer as configuracoes (mais pratico que usar o teclado do alarme)
