### ISSUE TITLE
suporte a homekit

### ISSUE THREAD

**Issue by caarlos0** [elvis-epx/alarme-intelbras#3]
baseado nesse projeto (e outros) e um monte de wireshark, escrevi uma bridge homekit pra amt8000!

suporta:

- armar/desarmar particoes
- anulacao temporaria de zonas
- sensores de movimento e de contato
- panico sonoro

Se alguem se interessar, tem coisas a serem feitas ainda... especialmente queria pegar o status das baterias...

https://github.com/caarlos0/homekit-amt8000

Ah, e muito obrigado pelo codigo aqui, me ajudou muito, especialmente no inicio!

**Comment by renatomarcio** [comment]
Que legal! Parabéns! Vou reservar um tempo para experimentar.

**Comment by elvis-epx** [comment]
Legal, nós também adicionamos recentemente o utilitário "comandar", que faz coisas parecidas via CLI.

A versão mais recente da publicação dos protocolos da Intelbras tem a especificação necessária para esse tipo de cliente (num formato horroroso, mas tem), então não precisei usar Wireshark.

**Comment by caarlos0** [comment]
Rapaz, não consegui essas docs aí, o que me mandaram não tinha absolutamente nada de útil hehe

**Comment by elvis-epx** [comment]
@caarlos0 peça a última versão da documentação usando aquele atendimento via WhatsApp. A parte interessante está na planilha "Mapa EEPROM AMT 8000 V22.xlsx" (sim, o conteúdo vai muito além de mapa de EEPROM). Na aba "App Mobile" há os comandos utilizados pela central AMT-8000, e na aba "Fields Description" tem os detalhes de cada comando.

**Comment by renatomarcio** [comment]
https://botminio.apps.intelbras.com.br/sdk-api/SDKCentraisDeAlarmeIntelbras-v1.0.1.zip

**Comment by caarlos0** [comment]
show, vou dar uma olhada!

Obrigado!
